name: MurderParty
version: 0.3.0
main: com.cameronlattz.murderparty.MurderParty
api-version: 1.15
softdepend: [WorldEdit, WorldGuard]
commands:
  murderparty:
    description: Murder Party
    aliases: [mp, mP, Mp, MP]
permissions:
  mp.start:
    description: Allows starting a MurderParty game
    default: op
  mp.end:
    description: Allows ending a MurderParty game
    default: op